export const ROOMS = [
  {
    id: 'royal-haven',
    name: 'Royal Haven',
    tagline: 'Family Suite',
    description: 'A spacious, family-friendly suite with three bedrooms and a bright living area, perfect for families or groups seeking a comfortable retreat in Abuja.',
    price_per_night: 250000,
    bedrooms: 3,
    size_sqm: 250,
    max_guests: 6,
    amenities: ['High-Speed WiFi', 'Smart TV', 'Swimming Pool', 'Netflix', 'Air Conditioning', 'Daily Housekeeping'],
    image_url: 'https://media.base44.com/images/public/6a5537674461cdc7bdad66cf/d7450e02f_generated_21bb45e6.png',
  },
  {
    id: 'majestic-deluxe',
    name: 'The Majestic Deluxe',
    tagline: 'Executive Suite',
    description: 'A luxurious room with an atmosphere oozing comfort and tranquility. Sharing a blend of luxury modern furnishings with panoramic city views.',
    price_per_night: 350000,
    bedrooms: 4,
    size_sqm: 320,
    max_guests: 8,
    amenities: ['High-Speed WiFi', 'Smart TV', 'Rooftop Pool', 'Gourmet Kitchen', '24/7 Concierge', 'Private Terrace'],
    image_url: 'https://media.base44.com/images/public/6a5537674461cdc7bdad66cf/ef518f0ee_generated_210486c6.png',
  },
  {
    id: 'luxe-manor',
    name: 'The Luxe Manor',
    tagline: 'Premium Suite',
    description: 'The ultimate luxury living experience offering a blend of modern aesthetics and timeless elegance. Our most exclusive residence.',
    price_per_night: 400000,
    bedrooms: 5,
    size_sqm: 450,
    max_guests: 10,
    amenities: ['High-Speed WiFi', 'Smart TV', 'Private Pool', 'Full Kitchen', 'Home Gym', 'Personal Butler', 'Private Cinema'],
    image_url: 'https://media.base44.com/images/public/6a5537674461cdc7bdad66cf/556ba3447_generated_e98d5d1f.png',
  },
];

export const CARS = [
  {
    id: 'luxurious-style',
    name: 'Luxurious Style',
    style: 'Sports Coupe',
    description: 'Experience the thrill of pure performance. This sports coupe delivers breathtaking acceleration and handles with surgical precision—for business or pure pleasure.',
    price_per_day: 150000,
    horsepower: 650,
    top_speed: '320 km/h',
    seats: 4,
    transmission: 'Automatic',
    features: ['Chauffeur Available', 'GPS Navigation', 'Premium Sound System', 'Leather Interior', 'Climate Control'],
    image_url: 'https://media.base44.com/images/public/6a5537674461cdc7bdad66cf/ad6539448_generated_e8ef4aa2.png',
  },
  {
    id: 'premium-style',
    name: 'Premium Style',
    style: 'Executive Sedan',
    description: 'Premium performance meets executive refinement. Offering top-tier luxury features and special promotions, perfect for business travel and special occasions.',
    price_per_day: 120000,
    horsepower: 450,
    top_speed: '280 km/h',
    seats: 5,
    transmission: 'Automatic',
    features: ['Chauffeur Available', 'GPS Navigation', 'Massage Seats', 'Ambient Lighting', 'Air Suspension'],
    image_url: 'https://media.base44.com/images/public/6a5537674461cdc7bdad66cf/8930a48a6_generated_66061811.png',
  },
  {
    id: 'elegant-style',
    name: 'Elegant Style',
    style: 'Luxury SUV',
    description: 'The top-of-the-line SUV with exceptional reliability and commanding presence. Perfect for families, airport transfers, and VIP transportation.',
    price_per_day: 180000,
    horsepower: 500,
    top_speed: '260 km/h',
    seats: 7,
    transmission: 'Automatic',
    features: ['Chauffeur Available', 'GPS Navigation', 'Premium Bose Sound', 'Panoramic Roof', 'Air Suspension', 'Night Vision'],
    image_url: 'https://media.base44.com/images/public/6a5537674461cdc7bdad66cf/6e5a5ceee_generated_3119a26d.png',
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    guest_name: 'Michael A.',
    guest_title: 'Business Executive',
    headline: '"Exceptional Service from Start to Finish."',
    body: "I rented one of Frensic Luxury's executive SUVs for a business trip, and the experience exceeded my expectations. The booking process was seamless, the vehicle arrived on time, looked brand new, and the chauffeur was punctual, courteous, and highly professional. Every detail reflected excellence. I highly recommend Frensic Luxury to anyone looking for premium transportation.",
    rating: 5,
    service_type: 'drive',
    avatar_url: 'https://media.base44.com/images/public/6a5537674461cdc7bdad66cf/22fde00dc_images2.jpg',
  },
  {
    id: 2,
    guest_name: 'Emily James',
    guest_title: 'Interior Designer',
    headline: '"A Truly Luxurious Stay."',
    body: "My family stayed in Frensic Luxury's 5-bedroom apartment during our holiday, and it felt like a five-star hotel with the comfort of home. The apartment was beautifully furnished, spacious, immaculately clean, and equipped with everything we needed. The customer service team was responsive and made our stay effortless. We'll definitely book again.",
    rating: 5,
    service_type: 'stay',
    avatar_url: 'https://media.base44.com/images/public/6a5537674461cdc7bdad66cf/85cc00370_images.jpg',
  },
  {
    id: 3,
    guest_name: 'David O.',
    guest_title: 'Tech Entrepreneur',
    headline: '"The Gold Standard of Luxury Rentals."',
    body: "I've used several luxury car rental companies over the years, but Frensic Luxury stands out for its professionalism and attention to detail. The entire process was smooth from booking to return. Their commitment to quality and customer satisfaction is truly impressive. I wouldn't hesitate to recommend them.",
    rating: 5,
    service_type: 'drive',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100',
  },
  {
    id: 4,
    guest_name: 'Sarah M.',
    guest_title: 'Corporate Events Manager',
    headline: '"Flawless Experience, Flawless Hospitality."',
    body: "Organized a corporate retreat using Frensic Luxury's apartment and transportation fleet. The coordination was impeccable—every vehicle arrived on time, the apartment exceeded our expectations, and the support team was available around the clock. This is what true luxury service looks like.",
    rating: 5,
    service_type: 'stay',
    avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
  },
];

export const FAQS = [
  { q: 'Are there extra charges to stay in the apartment?', a: 'No hidden charges. The price displayed covers your full stay including utilities, housekeeping, and standard amenities.' },
  { q: 'How do I make a reservation for the apartment?', a: 'You can book directly through our website using the Book Now page, or contact us via phone/email for personalized assistance.' },
  { q: 'Is there a swimming pool in the apartment?', a: 'Yes, all our suites have access to a private or shared pool depending on the suite. The Luxe Manor has an exclusive private pool.' },
  { q: 'Are meals and drinks included in the apartment?', a: 'Our suites come fully equipped with kitchen facilities. Catering services can be arranged on request for an additional fee.' },
  { q: 'Do I need to specifically book for an extra guest?', a: 'Yes, please indicate the number of guests during booking. Each suite has a maximum capacity and additional guests may incur additional charges.' },
];